### ISSUE TITLE
게시물 들어갔을 때 앱이 강제 종료 되는 에러

### ISSUE THREAD

**Issue by skykhs3** [sparcs-kaist/new-ara-app#69]
## Description 
스크롤 중 빈 공간이 생김

## To Reproduce
자유 게시판의 "터지는 게시판" 게시물 선택

## Expected behavior
정상적으로 웹뷰가 렌더링 되어야함.

## Error Log
```
I/ViewRootImpl@2cccd23[MainActivity](26788): ViewPostIme pointer 0
I/ViewRootImpl@2cccd23[MainActivity](26788): ViewPostIme pointer 1
I/flutter (26788): **********************************************
I/flutter (26788): BUILDAUTHORINFO INVOKED
I/flutter (26788): **********************************************
I/WebViewFactory(26788): Loading com.google.android.webview version 101.0.4951.61 (code 495106133)
W/g.sparcs.newar(26788): Accessing hidden method Landroid/os/Trace;->isTagEnabled(J)Z (greylist, reflection, allowed)
W/g.sparcs.newar(26788): Accessing hidden method Landroid/os/Trace;->traceBegin(JLjava/lang/String;)V (greylist, reflection, allowed)
W/g.sparcs.newar(26788): Accessing hidden method Landroid/os/Trace;->traceEnd(J)V (greylist, reflection, allowed)
W/g.sparcs.newar(26788): Accessing hidden method Landroid/os/Trace;->asyncTraceBegin(JLjava/lang/String;I)V (greylist, reflection, allowed)
W/g.sparcs.newar(26788): Accessing hidden method Landroid/os/Trace;->asyncTraceEnd(JLjava/lang/String;I)V (greylist, reflection, allowed)
I/cr_WVCFactoryProvider(26788): Loaded version=101.0.4951.61 minSdkVersion=29 isBundle=true multiprocess=true packageId=2
I/cr_LibraryLoader(26788): Successfully loaded native library
I/cr_CachingUmaRecorder(26788): Flushed 9 samples from 9 histograms.
D/ConnectivityManager(26788): requestNetwork; CallingUid : 10487, CallingPid : 26788
D/ConnectivityManager(26788): requestNetwork; CallingUid : 10487, CallingPid : 26788
W/g.sparcs.newar(26788): Accessing hidden method Landroid/media/AudioManager;->getOutputLatency(I)I (greylist, reflection, allowed)
W/cr_media(26788): Requires BLUETOOTH permission
I/mali_egl(26788): eglDestroySurface() in
I/mali_egl(26788): eglDestroySurface() out
I/PlatformViewsController(26788): Hosting view in view hierarchy for platform view: 0
I/mali_winsys(26788): new_window_surface() [1x1] return: 0x3000
W/Gralloc3(26788): allocator 3.x is not supported
I/flutter (26788): WebView is loading (progress: 10)
I/flutter (26788): WebView is loading (progress: 80)
I/flutter (26788): WebView is loading (progress: 100)
I/flutter (26788): WebView is loading (progress: 100)
I/flutter (26788): height fitted!!
I/flutter (26788): pageHeight: "4344" -> 4344.0
E/chromium(26788): [ERROR:skia_output_surface_impl.cc(979)] 
E/chromium(26788):   surface_size=975x11403
E/chromium(26788):   format=7
E/chromium(26788):   color_type=4
E/chromium(26788):   backend_format.isValid()=1
E/chromium(26788):   backend_format.backend()=0
E/chromium(26788):   backend_format.asGLFormat()=1
E/chromium(26788):   backend_format.asVkFormat()=0
E/chromium(26788):   backend_format.asVkFormat() vk_format=0
E/chromium(26788):   surface_origin=1
E/chromium(26788):   willGlFBO0=1
E/OpenGLRenderer(26788): [SurfaceTexture-0-26788-0] bindTextureImage: error binding external image: 0x501
E/flutter (26788): [ERROR:flutter/fml/platform/android/jni_util.cc(204)] java.lang.RuntimeException: Error during updateTexImage (see logcat for details)
E/flutter (26788):      at android.graphics.SurfaceTexture.nativeUpdateTexImage(Native Method)
E/flutter (26788):      at android.graphics.SurfaceTexture.updateTexImage(SurfaceTexture.java:248)
E/flutter (26788):      at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.updateTexImage(SurfaceTextureWrapper.java:55)
E/flutter (26788): 
F/flutter (26788): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1339)] Check failed: fml::jni::CheckException(env). 
F/libc    (26788): Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 27781 (1.raster), pid 26788 (g.sparcs.newara)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'samsung/star2lteks/star2lteks:10/QP1A.190711.020/G965NKSU5FVG2:user/release-keys'
Revision: '26'
ABI: 'arm64'
Timestamp: 2024-02-04 21:39:20+0900
pid: 26788, tid: 27781, name: 1.raster  >>> org.sparcs.newara <<<
uid: 10487
signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1339)] Check failed: fml::jni::CheckException(env). 
'
    x0  0000000000000000  x1  0000000000006c85  x2  0000000000000006  x3  0000007e73e15b20
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  0000000000000080
    x8  00000000000000f0  x9  0000007f688795e0  x10 0000000000000000  x11 0000000000000001
    x12 000000000b78ca08  x13 0000000000000003  x14 0000000000000000  x15 0000000000000000
    x16 0000007f689478c0  x17 0000007f68924880  x18 0000007e72d50000  x19 00000000000000ac
    x20 00000000000068a4  x21 00000000000000b2  x22 0000000000006c85  x23 00000000ffffffff
    x24 0000007e73e163c8  x25 0000007ed40d93d8  x26 0000000000000001  x27 0000000000000000
    x28 0000000000000001  x29 0000007e73e15bd0
    sp  0000007e73e15b00  lr  0000007f688d8330  pc  0000007f688d8360
backtrace:
      #00 pc 0000000000083360  /apex/com.android.runtime/lib64/bionic/libc.so (abort+176) (BuildId: 3f350ca06c3b80560f65755286daf320)
      #01 pc 000000000167de4c  /data/app/org.sparcs.newara-opCjwxvlNbbaO-esr6w7Aw==/lib/arm64/libflutter.so (BuildId: bf7fb15302b37bb0d48c211473046419503e6aa0)
```

## Screenshots

https://github.com/sparcs-kaist/new-ara-app/assets/5186472/d07d9561-4967-4b79-b023-abf6462ce367

## Development Environment
 - OS: macOS

## Test Environment
 - Device: Samsung Galaxy S9+
 - OS: Android 10
 - App Version: dev(5a3e2f34b355f43aed2e2f47b373f4fea3422023)

**Comment by sangohkim** [comment]
@skykhs3 혹시 '터지는 게시판' 원글이 뭐였는지 아시나요?

**Comment by sangohkim** [comment]
@skykhs3 우선 Device만 Pixel 7으로 바뀌고 OS, App Version 모두 동일하게 했을 때는 에러가 발생하지 않고 잘 열렸습니다. 에러 로그 위주로 원인을 한번 찾아보도록 하겠습니다.
