### ISSUE TITLE
[BUG] MainPage 에러

### ISSUE THREAD

**Issue by sangohkim** [sparcs-kaist/new-ara-app#73]
## Description 
로그인 후 메인페이지가 나올 때 또는 다른 탭에서 메인페이지 탭으로 옮겼을 때 에러가 발생합니다.

## To Reproduce
fix/disable-api-post 에서 빌드한 후 확인할 수 있습니다. 기존 앱을 삭제하시고 다시 빌드하셨을 때 더 잘 확인할 수 있는 것 같습니다.

## Expected behavior
메인페이지가 정상적으로 보여야 함.

## Error Log
```
The following RangeError was thrown building MainPage(dirty, dependencies: [MediaQuery], state:
_MainPageState#6dee7):
RangeError (index): Invalid value: Valid value range is empty: 0

The relevant error-causing widget was:
  MainPage
  MainPage:file:///Users/sangohkim/ksodev/SPARCS/new-ara-app/lib/pages/main_navigation_tab_page.dart:26:11

When the exception was thrown, this was the stack:
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
growable_array.dart:264
#1      _MainPageState.build (package:new_ara_app/pages/main_page.dart:723:60)
main_page.dart:723
#2      StatefulElement.build (package:flutter/src/widgets/framework.dart:5409:27)
framework.dart:5409
#3      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5297:15)
framework.dart:5297
#4      StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462:11)
framework.dart:5462
#5      Element.rebuild (package:flutter/src/widgets/framework.dart:5016:7)
framework.dart:5016
#6      BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2779:19)
framework.dart:2779
#7      WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:916:21)
binding.dart:916
#8      RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:360:5)
binding.dart:360
#9      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1297:15)
binding.dart:1297
#10     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1227:9)
binding.dart:1227
#11     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1085:5)
binding.dart:1085
#12     _invoke (dart:ui/hooks.dart:170:13)
hooks.dart:170
#13     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:401:5)
platform_dispatcher.dart:401
#14     _drawFrame (dart:ui/hooks.dart:140:31)
```

## Screenshots
![Simulator Screenshot - iPhone 15 - 2024-02-06 at 18 30 02](https://github.com/sparcs-kaist/new-ara-app/assets/48672097/7f5ce96b-d632-4e5d-9d97-a21dc6ce4295)

## Development Environment
 - OS: macOS

## Test Environment
 - Device: iPhone 15
 - OS: iOS 17.2
 - App Version: fix/disable-api-post

**Comment by sangohkim** [comment]
csrftoken 이슈로 다시 열겠습니다.
